@startuml
|Kunde|
|Fog Web Applikation|
|Sælger|

|Kunde|
start
note right: Fortsættelse fra side 2 (B)

|Kunde|
partition mail #LightSkyBlue {
:Notifikation: Tilbud uden stykliste modtaget på "din side";
}
partition fil #LightGreen {
:Tilbud;
:Tegning;
}
if (Accepter tilbud?) is (Nej) then
  stop
else (Ja)
  |Fog Web Applikation|
  :Modtag betaling;
  :Send ordre ordrebekræftelse;

  |Kunde|
  partition mail #LightSkyBlue {
  :Notifikation: Ordrebekræftelse inkl. stykliste modtaget på "din side";
  }
  partition fil #LightGreen {
  :Ordrebekræftelse;
  :Stykliste;
  :Tegning;
  }
endif
stop
@enduml

