@startuml

class Account
{
email
password
address
zip
city
phone
}

class Customer
{
}

class Seller
{
}

class Shed
{
}

class Price
{
cost price
coverage/margin
total price
}

class Measurements
{
length
width
}

class BillOfMaterials
{
}

class MaterialCategory
{
wood & roofing
fittings & fasteners
}

class Material
{
quantity
description
use
unit price
}

class MaterialCatalog
{
}

class Inquiry
{
requestDate
inquiryStatus
}

class Offer
{
description
date created
accepted
rejected
expired
}

class Order
{
orderDateTime
paid
cancelled
}

class Carport
{
}

class CarportDrawing
{
top view
side view
}

class Notification
{
inquiry received e-mail
offer sent e-mail
order confirmation e-mail
}

Account <|- Customer
Account <|- Seller

Customer "1" -- "0..*" Inquiry : places
Inquiry "1" -- "1" Carport : contains
Inquiry "1" -- "0..1" Offer : generates
Seller "1" -- "0..*" Offer : handles/edits
Seller "1" -- "0..*" MaterialCatalog : manages

Customer "1..*" -- "0..*" Notification : receives
Inquiry "1" -- "1" Notification : triggers
Offer "1" -- "1" Notification : triggers
Order "1" -- "1" Notification : triggers

Offer "0..*" -- "1" Customer : sent to
Offer "1" -- "0..1" Order : becomes (if accepted)
Offer "1" -- "1" Price
Offer "1" -- "1" CarportDrawing

Order "0..*" -- "1" Customer : belongs to
Order "1" -- "1" BillOfMaterials : includes

Carport "1" -- "1" Measurements
Carport "1" -- "0..1" Shed
Carport "0..*" -- "*" Material : uses
Shed "0..1" -- "1" Measurements
Shed "0..1" -- "*" Material : uses
Material "1" -- "1" MaterialCategory : is type of
Material "0..*" -- "1" MaterialCatalog : contains

BillOfMaterials "1" -- "1..*" Material : contains

@enduml