-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.zip_code
(
    zip_code integer NOT NULL,
    city character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT zip_code_pkey PRIMARY KEY (zip_code)
    );

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying(150) COLLATE pg_catalog."default" NOT NULL,
    zip_code integer NOT NULL,
    street character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'CUSTOMER'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS public.shed
(
    shed_id serial NOT NULL,
    length integer NOT NULL,
    width integer NOT NULL,
    shed_placement character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'FULL_WIDTH'::character varying,
    CONSTRAINT shed_pkey PRIMARY KEY (shed_id)
    );

CREATE TABLE IF NOT EXISTS public.carport
(
    carport_id serial NOT NULL,
    length integer NOT NULL,
    width integer NOT NULL,
    shed_id integer,
    roof_type character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'FLAT'::character varying,
    CONSTRAINT carport_pkey PRIMARY KEY (carport_id),
    CONSTRAINT carport_shed_id_unique UNIQUE (shed_id)
    );

CREATE TABLE IF NOT EXISTS public.material
(
    material_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category character varying COLLATE pg_catalog."default" NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    material_width integer,
    material_height integer,
    unit character varying(20) COLLATE pg_catalog."default" NOT NULL,
    usage character varying COLLATE pg_catalog."default",
    CONSTRAINT material_pkey PRIMARY KEY (material_id)
    );

CREATE TABLE IF NOT EXISTS public.material_variant
(
    material_variant_id serial NOT NULL,
    material_id integer NOT NULL,
    variant_length integer,
    unit_price double precision NOT NULL,
    pieces_per_unit integer,
    CONSTRAINT material_variant_pkey PRIMARY KEY (material_variant_id)
    );

CREATE TABLE IF NOT EXISTS public."orders"
(
    order_id serial NOT NULL,
    customer_id integer NOT NULL,
    seller_id integer,
    carport_id integer NOT NULL,
    request_created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone,
    offer_valid_days integer,
    order_status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    customer_comment text COLLATE pg_catalog."default",
    coverage_percentage double precision,
    cost_price double precision,
    CONSTRAINT order_pkey PRIMARY KEY (order_id)
    );

CREATE TABLE IF NOT EXISTS public. material_line
(
    material_line_id serial NOT NULL,
    order_id integer NOT NULL,
    material_variant_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT material_line_pkey PRIMARY KEY (material_line_id)
    );

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_zip_code_fk FOREIGN KEY (zip_code)
    REFERENCES public.zip_code (zip_code) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.carport
    ADD CONSTRAINT carport_shed_fk FOREIGN KEY (shed_id)
    REFERENCES public. shed (shed_id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.material_variant
    ADD CONSTRAINT material_variant_material_fk FOREIGN KEY (material_id)
    REFERENCES public.material (material_id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."orders"
    ADD CONSTRAINT order_customer_fk FOREIGN KEY (customer_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."orders"
    ADD CONSTRAINT order_seller_fk FOREIGN KEY (seller_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."orders"
    ADD CONSTRAINT order_carport_fk FOREIGN KEY (carport_id)
    REFERENCES public.carport (carport_id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.material_line
    ADD CONSTRAINT material_line_order_fk FOREIGN KEY (order_id)
    REFERENCES public."orders" (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;

ALTER TABLE IF EXISTS public. material_line
    ADD CONSTRAINT material_line_variant_fk FOREIGN KEY (material_variant_id)
    REFERENCES public.material_variant (material_variant_id) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE RESTRICT;

CREATE SCHEMA IF NOT EXISTS test;

END;